//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace _20201018_MVC5_CLASS_01.Models
{
    public class MustEvenAttribute : DataTypeAttribute
    {
        public MustEvenAttribute() : base(DataType.Text)
        {
            ErrorMessage = "請輸入偶數";
        }
        
        public override bool IsValid(object value)
        {
            if(value == null)
            {
                return true;
            }

            int num = Convert.ToInt32(value);
            return (num % 2 == 0);
        }
    }
}